theme: minima

title: Jekyll Pages
author: Christian A. Gonzalez
email: chartgonz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The greatest learning/testing page in the world!

# social links
twitter_username: SS_SolidHandou # DO NOT include the @ character, or else the build will fail!
github_username:  SolidHandou # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
